// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Api.Data;

#nullable disable

namespace TaskManagement.Api.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("TaskManagement.Api.Models.TaskItem", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<decimal?>("ActualHours").HasColumnType("decimal(9,2)");
            b.Property<int?>("AssignedToUserId").HasColumnType("int");
            b.Property<DateTime?>("CompletedDate").HasColumnType("datetime2");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<int>("CreatedByUserId").HasColumnType("int");
            b.Property<string>("Description").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<DateTime?>("DueDate").HasColumnType("datetime2");
            b.Property<decimal?>("EstimatedHours").HasColumnType("decimal(9,2)");
            b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<int>("Priority").HasColumnType("int");
            b.Property<int>("ProgressPercent").HasColumnType("int");
            b.Property<DateTime?>("StartDate").HasColumnType("datetime2");
            b.Property<int>("Status").HasColumnType("int");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");

            b.HasKey("Id");
            b.HasIndex("AssignedToUserId");
            b.ToTable("Tasks");
        });

        modelBuilder.Entity("TaskManagement.Api.Models.User", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<int>("Role").HasColumnType("int");

            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("TaskManagement.Api.Models.TaskItem", b =>
        {
            b.HasOne("TaskManagement.Api.Models.User", "AssignedTo")
                .WithMany("AssignedTasks")
                .HasForeignKey("AssignedToUserId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("AssignedTo");
        });

        modelBuilder.Entity("TaskManagement.Api.Models.User", b =>
        {
            b.Navigation("AssignedTasks");
        });
#pragma warning restore 612, 618
    }
}
